""".

Revision ID: 26a6d6043c01
Revises: 489bf72871fd
Create Date: 2026-04-03 18:00:11.776946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26a6d6043c01'
down_revision: Union[str, Sequence[str], None] = '489bf72871fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'email_verification_tokens', ['id'])
    op.create_unique_constraint(None, 'password_reset_tokens', ['id'])
    op.create_unique_constraint(None, 'refresh_token', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'refresh_token', type_='unique')
    op.drop_constraint(None, 'password_reset_tokens', type_='unique')
    op.drop_constraint(None, 'email_verification_tokens', type_='unique')
    # ### end Alembic commands ###
