"""type

Revision ID: 6b9448bb4925
Revises: 26a6d6043c01
Create Date: 2026-04-03 18:45:27.111369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b9448bb4925'
down_revision: Union[str, Sequence[str], None] = '26a6d6043c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('conversion_type', sa.Enum('convert_pdf_to_ppt', 'convert_docx_to_pdf', 'convert_pdf_to_docx', 'convert_pptx_to_pdf', 'compress_pdf', 'merge_pdf', name='job_conversion_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'conversion_type')
    # ### end Alembic commands ###
